In [2]:
import numpy as np

## Exercise 1
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1. <br>
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [26]:
x = np.array([1, 2, 3, 5])
N = 4
np.vander(x, N, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [27]:
np.vander(x, N, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [33]:
def fun(X, N, increasing):
    new_X = np.empty((len(X), N))
    if(increasing == False):
        for j in range(N):
            for i in range(len(X)):
                new_X[i,j] = pow(X[i], N-j-1)
    else:
        for j in range(N):
            for i in range(len(X)):
                new_X[i,j] = pow(X[i], j)
                
    return new_X
        

In [35]:
X = np.array([1, 2, 3, 5])
N = 4

print(fun(X, N, True))

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   5.  25. 125.]]


In [36]:
print(fun(X, N, False))

[[  1.   1.   1.   1.]
 [  8.   4.   2.   1.]
 [ 27.   9.   3.   1.]
 [125.  25.   5.   1.]]


## Exercise 2
Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [47]:
Y = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
N = len(Y)
for i in range(0,N-k+1,1):
    el = 0.0
    for j in range(i,i+k,1):
        el += Y[j]
        
    print(el)
    

15.0
14.0
17.0
20.0
29.0
86.0
148.0
218.0
252.0
280.0
349.0
